# Shell variables
# Generated by 'wal'
wallpaper='/home/xmo/Wallpapers/SwordGirl.jpg'

# Special
background='#030202'
foreground='#e6e2e3'
cursor='#e6e2e3'

# Colors
color0='#030202'
color1='#D70E1E'
color2='#F6112A'
color3='#B85B53'
color4='#8D7A8B'
color5='#A396A4'
color6='#CBAFB4'
color7='#e6e2e3'
color8='#a19e9e'
color9='#D70E1E'
color10='#F6112A'
color11='#B85B53'
color12='#8D7A8B'
color13='#A396A4'
color14='#CBAFB4'
color15='#e6e2e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
