# Shell variables
# Generated by 'wal'
wallpaper='/home/xmo/Wallpapers/cyberpunk.jpg'

# Special
background='#0c060f'
foreground='#93c5d2'
cursor='#93c5d2'

# Colors
color0='#0c060f'
color1='#084756'
color2='#1C5665'
color3='#545E68'
color4='#96686F'
color5='#3F5A96'
color6='#AC42BA'
color7='#93c5d2'
color8='#668993'
color9='#084756'
color10='#1C5665'
color11='#545E68'
color12='#96686F'
color13='#3F5A96'
color14='#AC42BA'
color15='#93c5d2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
