--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xmo/Wallpapers/rosegirl.jpg"

-- Special
background="#0a0a0b"
foreground="#d1cacb"
cursor="#d1cacb"

-- Colors
color0="#0a0a0b"
color1="#695655"
color2="#872D29"
color3="#8B7172"
color4="#937F81"
color5="#99888A"
color6="#A89496"
color7="#d1cacb"
color8="#928d8e"
color9="#695655"
color10="#872D29"
color11="#8B7172"
color12="#937F81"
color13="#99888A"
color14="#A89496"
color15="#d1cacb"
