# Shell variables
# Generated by 'wal'
wallpaper='/home/xmo/Pictures/Wallpapers/Cityline.jpg'

# Special
background='#0F1D21'
foreground='#e9e3de'
cursor='#e9e3de'

# Colors
color0='#0F1D21'
color1='#6B5F5F'
color2='#8C7066'
color3='#91847B'
color4='#B8ABA9'
color5='#C8B7B6'
color6='#D8CCC8'
color7='#e9e3de'
color8='#a39e9b'
color9='#6B5F5F'
color10='#8C7066'
color11='#91847B'
color12='#B8ABA9'
color13='#C8B7B6'
color14='#D8CCC8'
color15='#e9e3de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
