--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xmo/Wallpapers/SwordGirl.jpg"

-- Special
background="#030202"
foreground="#e6e2e3"
cursor="#e6e2e3"

-- Colors
color0="#030202"
color1="#D70E1E"
color2="#F6112A"
color3="#B85B53"
color4="#8D7A8B"
color5="#A396A4"
color6="#CBAFB4"
color7="#e6e2e3"
color8="#a19e9e"
color9="#D70E1E"
color10="#F6112A"
color11="#B85B53"
color12="#8D7A8B"
color13="#A396A4"
color14="#CBAFB4"
color15="#e6e2e3"
