--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xmo/Pictures/Wallpapers/Cityline.jpg"

-- Special
background="#0F1D21"
foreground="#e9e3de"
cursor="#e9e3de"

-- Colors
color0="#0F1D21"
color1="#6B5F5F"
color2="#8C7066"
color3="#91847B"
color4="#B8ABA9"
color5="#C8B7B6"
color6="#D8CCC8"
color7="#e9e3de"
color8="#a39e9b"
color9="#6B5F5F"
color10="#8C7066"
color11="#91847B"
color12="#B8ABA9"
color13="#C8B7B6"
color14="#D8CCC8"
color15="#e9e3de"
